stream:
  image:
    repository: blockchainetl/eos-etl
    tag: 1.0.0-streaming
    pullPolicy: IfNotPresent
config:
  LAG_BLOCKS: 0
  MAX_WORKERS: 10
  PROVIDER_URI: http://api.main.alohaeos.com
  PUB_SUB_TOPIC_PREFIX: projects/<YOUR_PROJECT_HERE>/topics/crypto_eos
  ROOT_ENTITY_TYPE: block
  GCS_PREFIX: gs://<YOUR_BUCKET_HERE>/eos-etl/streaming
