# Default values for blockchain-etl-streaming.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

config:
  PROVIDER_URI: "http://user:pass@localhost:8332"
  STREAM_OUTPUT: "projects/<your-project>/topics/crypto_ethereum"
  GCS_PREFIX: "gs://<your-bucket>/ethereum-etl/streaming"
  LAG_BLOCKS: "10"
  MAX_WORKERS: "4"
  ENTITY_TYPES: ""
  CHAIN: "bitcoin"
  ROOT_ENTITY_TYPE: "" # "block", "trace"

lsb_file: last_synced_block.txt
lsb_path: /var/blockchain-etl
pid_file: stream.pid

init:
  image:
    repository: google/cloud-sdk
    tag: 264.0.0-alpine
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
stream:
  image:
    repository: blockchainetl/bitcoin-etl
    tag: 1.4.0-streaming
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "350m"
  env:
    LAST_SYNCED_BLOCK_FILE_MAX_AGE_IN_SECONDS: "600"
  livenessProbe:
    initialDelaySeconds: "300"
    periodSeconds: "300"

upload:
  image:
    repository: google/cloud-sdk
    tag: 264.0.0-alpine
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

cloudSqlProxy:
  enabled: false
  instanceConnectionName: "project_id:region:cloud_sql_instance_name"
  port: 5432
  image:
    repository: gcr.io/cloudsql-docker/gce-proxy
    tag: 1.14
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

securityContext: {}
#  runAsUser: 1000
#  runAsGroup: 1000
#  fsGroup: 1000


nodeSelector: {}

tolerations: []

affinity: {}
