namePrefix: dash-
commonLabels:
  chain: dash
bases:
- ../../../bitcoin_base
configMapGenerator:
- name: streaming-app-config
  behavior: merge
  literals:
    - PROVIDER_URI=http://user:pass@localhost:8332
    - GCS_PREFIX=gs://<your-bucket>/dash-etl/streaming
    - PUB_SUB_TOPIC_PREFIX=projects/<your-project>/topics/crypto_dash
    - LAG_BLOCKS=24
    - CHAIN=dash