apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: streaming-app-deployment
spec:
  template:
    spec:
      containers:
      - name: stream
        image: blockchainetl/ethereum-etl:1.3.1-streaming
        args:
          - "stream"
          - "--provider-uri=$(PROVIDER_URI)"
          - "--last-synced-block-file=/var/blockchain-etl/last_synced_block.txt"
          - "--output=$(PUB_SUB_TOPIC_PREFIX)"
          - "--lag=$(LAG_BLOCKS)"
          - "--max-workers=$(MAX_WORKERS)"
          - "--batch-size=10"
          - "--block-batch-size=1"
          - "--entity-types=$(ENTITY_TYPES)"
          - "--pid-file=/var/blockchain-etl/stream.pid"
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: PROVIDER_URI
          valueFrom:
            configMapKeyRef:
              name: streaming-app-config
              key: PROVIDER_URI
        - name: PUB_SUB_TOPIC_PREFIX
          valueFrom:
            configMapKeyRef:
              name: streaming-app-config
              key: PUB_SUB_TOPIC_PREFIX
        - name: LAG_BLOCKS
          valueFrom:
            configMapKeyRef:
              name: streaming-app-config
              key: LAG_BLOCKS
        - name: MAX_WORKERS
          valueFrom:
            configMapKeyRef:
              name: streaming-app-config
              key: MAX_WORKERS
        - name: ENTITY_TYPES
          valueFrom:
            configMapKeyRef:
              name: streaming-app-config
              key: ENTITY_TYPES
        - name: LAST_SYNCED_BLOCK_FILE_MAX_AGE_IN_SECONDS
          value: "600"

