apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: streaming-app-deployment
spec:
  template:
    spec:
      containers:
      - name: stream
        image: blockchainetl/bitcoin-etl:1.3.1-streaming
        args:
          - "stream"
          - "--provider-uri=$(PROVIDER_URI)"
          - "--last-synced-block-file=/var/blockchain-etl/last_synced_block.txt"
          - "--output=$(PUB_SUB_TOPIC_PREFIX)"
          - "--chain=$(CHAIN)"
          - "--lag=$(LAG_BLOCKS)"
          - "--max-workers=$(MAX_WORKERS)"
          - "--batch-size=5"
          - "--block-batch-size=1"
          - "--pid-file=/var/blockchain-etl/stream.pid"
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: LAST_SYNCED_BLOCK_FILE_MAX_AGE_IN_SECONDS
          value: "7200"
        envFrom:
          - configMapRef:
              name: streaming-app-config
        livenessProbe:
          initialDelaySeconds: 600
          periodSeconds: 600
