stream:
  image:
    repository: blockchainetl/ethereum-etl
    tag: 1.5.1
config:
  PROVIDER_URI: https://mainnet.infura.io
  ENTITY_TYPES: block,transaction,log,token_transfer
  LAG_BLOCKS: 18
  CHAIN: null
