namePrefix: bitcoin-cash-
commonLabels:
  chain: bitcoin_cash
bases:
- ../../../bitcoin_base
configMapGenerator:
- name: streaming-app-config
  behavior: merge
  literals:
    - PROVIDER_URI=http://user:pass@localhost:8332
    - GCS_PREFIX=gs://<your-bucket>/bitcoin_cash-etl/streaming
    - PUB_SUB_TOPIC_PREFIX=projects/<your-project>/topics/crypto_bitcoin_cash
    - LAG_BLOCKS=3
    - CHAIN=bitcoin_cash