namePrefix: zcash-
commonLabels:
  chain: zcash
bases:
- ../../../bitcoin_base
configMapGenerator:
- name: streaming-app-config
  behavior: merge
  literals:
    - PROVIDER_URI=http://user:pass@localhost:8332
    - GCS_PREFIX=gs://<your-bucket>/zcash-etl/streaming
    - PUB_SUB_TOPIC_PREFIX=projects/<your-project>/topics/crypto_zcash
    - LAG_BLOCKS=3
    - CHAIN=zcash