namePrefix: litecoin-
commonLabels:
  chain: litecoin
bases:
- ../../../bitcoin_base
configMapGenerator:
- name: streaming-app-config
  behavior: merge
  literals:
    - PROVIDER_URI=http://user:pass@localhost:8332
    - GCS_PREFIX=gs://<your-bucket>/litecoin-etl/streaming
    - PUB_SUB_TOPIC_PREFIX=projects/<your-project>/topics/crypto_litecoin
    - LAG_BLOCKS=12
    - CHAIN=litecoin